---
- include: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'
  tags:
    - nexpose
    - firewall
    - certs

- include: setup-Debian.yml
  when: ansible_os_family == 'Debian'
  tags:
    - nexpose
    - firewall
    - certs

- name: Install support packages
  package:
    name: screen
    state: latest
  tags:
    - nexpose
    - nexpose-packages

- name: Check if installer is already downloaded
  stat:
    path: /var/tmp/NeXposeSetup-Linux64.bin
  register: install_file_check
  tags:
    - nexpose

- name: Download nexpose installer
  get_url:
    url: "{{ nexpose_download_url }}"
    dest: /var/tmp
    mode: 0700
  when: not install_file_check.stat.exists
  tags:
    - nexpose

# Look in /opt/rapid7/nexpose/.install4j/response.varfile for available variables
# This command comes from this post: https://community.rapid7.com/thread/2169
- name: Install nexpose
  command: >
    /var/tmp/NeXposeSetup-Linux64.bin -q -overwrite
    -Vfirstname='{{ nexpose_first_name }}'
    -Vlastname='{{ nexpose_last_name }}'
    -Vcompany='{{ nexpose_company_name }}'
    -Vusername='{{ nexpose_logon_username }}'
    -Vpassword1='{{ nexpose_logon_password }}'
    -Vpassword2='{{ nexpose_logon_password }}'
    -Vsys.installationDir='{{ nexpose_install_dir }}'
    -Vsys.component.typical\$Boolean={{ nexpose_component_typical }}
    -Vsys.component.engine\$Boolean={{ nexpose_engine }}
    -VinitService\$Boolean={{ nexpose_init_service }}
    -Dinstall4j.suppressUnattendedReboot='{{ nexpose_suppress_unattended_reboot }}'
  args:
    creates: /opt/rapid7/nexpose
  register: nexpose_install
  failed_when: nexpose_install.stdout.find('failed') != -1 or nexpose_install.stderr
  no_log: True
  tags:
    - nexpose
    - install

- name: Start and enable Nexpose
  service:
    name: "{{ nexpose_service_name }}"
    enabled: yes
    state: started
  tags:
    - nexpose

- name: Wait for nse.xml
  wait_for:
    path: "{{ nexpose_install_dir }}/nse/conf/nse.xml"
    delay: 10
  when: nexpose_engine
  tags:
    - nexpose
    - install

- name: Set Nexpose Engine port
  replace:
    backup: yes
    dest: "{{ nexpose_install_dir }}/nse/conf/nse.xml"
    regexp: 'port="\d+"'
    replace: 'port="{{ nexpose_engine_port }}"'
  when: nexpose_engine
  notify: restart nexpose
  tags:
    - nexpose
    - install
    - fwconfig

- name: Wait for nsc.xml
  wait_for:
    path: "{{ nexpose_install_dir }}/nsc/conf/httpd.xml"
    delay: 30
  when: not nexpose_engine
  tags:
    - nexpose
    - install

- name: Set Nexpose Console port
  lineinfile:
    state: present
    backrefs: yes
    backup: yes
    dest: "{{ item.dest }}"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    backup: yes
  with_items:
    - {
        dest: '{{ nexpose_install_dir }}/nsc/conf/httpd.xml',
        regexp: '^(<server port\s+)= "\d+"',
        line: '\1= "{{ nexpose_console_port }}"'
      }
    - {
        dest: '{{ nexpose_install_dir }}/nsc/conf/nsc.xml',
        regexp: '^( <WebServer port=")\d+"(.*)$',
        line: '\1{{ nexpose_console_port }}\2"'
      }
  when: not nexpose_engine
  notify: restart nexpose
  tags:
    - nexpose
    - install
    - fwconfig

# - name: Remove nexpose installer
#   file: /tmp/NeXposeSetup-Linux64.bin state=absent
#   tags: [ 'nexpose' ]

- name: Copy CA Certs to be added to the keystore
  copy:
    src: "{{ item.name }}"
    dest: "{{ nexpose_ssl_cert_path }}"
    owner: root
    group: root
    mode: 0644
  with_items: "{{ nexpose_cacerts }}"
  tags:
    - nexpose
    - certs

- name: Add or remove CA Certs to/from key store
  java_keystore:
    cert: "{{ nexpose_ssl_cert_path }}/{{ item.name }}"
    keystore: 'cacerts'
    password: 'changeit'
    alias: "{{ item.alias }}"
    state: "{{ item.state }}"
  with_items: "{{ nexpose_cacerts }}"
  tags:
    - nexpose
    - certs

- name: Use SIGTERM to quit Nexpose in init script
  lineinfile:
    state: present
    backup: yes
    backrefs: yes
    dest: /etc/init.d/{{ nexpose_service_name }}
    regexp: '^(\s+) kill -\d+ (.*)'
    line: '\1 kill -15 \2'
  when: ansible_os_family == 'RedHat'
  tags:
    - nexpose
    - certs

- name: Directions for connecting to Console
  debug:
    msg: "1) ssh in to Engine   2) sudo screen -r   3) show consoles   4) enable console [number]   5) Ctrl-A Ctrl-D"
  tags:
    - nexpose
    - debug

# How to see what's in the keystore
# /opt/rapid7/nexpose/_jvm*/bin/keytool -list -v -keystore /opt/rapid7/nexpose/_jvm*/lib/security/cacerts
# Default password is 'changeit'
