---
- name: Install support packages
  package:
    name: screen
    state: present
  tags:
    - nexpose
    - nexpose-packages

- name: Check if installer is already downloaded
  stat:
    path: /var/tmp/Rapid7Setup-Linux64.bin
  register: install_file_check
  tags:
    - nexpose

- name: Download nexpose installer
  get_url:
    url: "{{ nexpose_download_url }}"
    dest: /var/tmp
    mode: 0700
  when: not install_file_check.stat.exists
  tags:
    - nexpose

- name: Disable SELinux
  selinux:
    state: disabled
  tags:
    - nexpose

- name: Write install file
  copy:
      dest: "/var/tmp/nexposeenginevar.txt"
      content: |
        communicationDirectionChoice$Integer=0
        company={{ nexpose_company_name }}
        dbPort=5432
        firstname={{ nexpose_first_name }}
        lastname={{ nexpose_last_name }}
        port=8443
        proxyHost=
        proxyPort=
        sys.adminRights$Boolean=true
        sys.component.engine$Boolean=true
        sys.component.typical$Boolean=false
        sys.installationDir=/opt/rapid7/nexpose
        sys.languageId=en
        sys.programGroupDisabled$Boolean=true

# Look in /opt/rapid7/nexpose/.install4j/response.varfile for available variables
# This command comes from this post: https://community.rapid7.com/thread/2169
- name: Install nexpose
  command: >
    /var/tmp/Rapid7Setup-Linux64.bin -q -overwrite -varfile /var/tmp/nexposeenginevar.txt
  args:
    creates: /opt/rapid7/nexpose
  register: nexpose_install
  ignore_errors: yes
  no_log: True
  tags:
    - nexpose
    - install

- name: Start and enable Nexpose
  service:
    name: "{{ nexpose_service_name }}"
    enabled: yes
    state: started
  tags:
    - nexpose

- name: Wait for nse.xml
  wait_for:
    path: "{{ nexpose_install_dir }}/nse/conf/nse.xml"
    delay: 10
  when: nexpose_engine
  tags:
    - nexpose
    - install

- name: Set Nexpose Engine port
  replace:
    backup: yes
    dest: "{{ nexpose_install_dir }}/nse/conf/nse.xml"
    regexp: 'port="\d+"'
    replace: 'port="{{ nexpose_engine_port }}"'
  when: nexpose_engine
  notify: restart nexpose
  tags:
    - nexpose
    - install
    - fwconfig

- name: Wait for nsc.xml
  wait_for:
    path: "{{ nexpose_install_dir }}/nsc/conf/httpd.xml"
    delay: 30
  when: not nexpose_engine
  tags:
    - nexpose
    - install

- name: Set Nexpose Console port
  lineinfile:
    state: present
    backrefs: yes
    backup: yes
    dest: "{{ item.dest }}"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
    - {
        dest: '{{ nexpose_install_dir }}/nsc/conf/httpd.xml',
        regexp: '^(<server port\s+)= "\d+"',
        line: '\1= "{{ nexpose_console_port }}"'
      }
    - {
        dest: '{{ nexpose_install_dir }}/nsc/conf/nsc.xml',
        regexp: '^( <WebServer port=")\d+"(.*)$',
        line: '\1{{ nexpose_console_port }}\2"'
      }
  when: not nexpose_engine
  notify: restart nexpose
  tags:
    - nexpose
    - install
    - fwconfig

# - name: Remove nexpose installer
#   file: /tmp/NeXposeSetup-Linux64.bin state=absent
#   tags: [ 'nexpose' ]

#- name: Use SIGTERM to quit Nexpose in init script
#  lineinfile:
#    state: present
#    backup: yes
#    backrefs: yes
#    dest: /etc/init.d/{{ nexpose_service_name }}
#    regexp: '^(\s+) kill -\d+ (.*)'
#    line: '\1 kill -15 \2'
#  when: ansible_os_family == 'RedHat'
#  tags:
#    - nexpose
#    - certs

- name: Directions for connecting to Console
  debug:
    msg: "1) ssh in to Engine   2) sudo screen -r   3) show consoles   4) enable console [number]   5) Ctrl-A Ctrl-D"
  tags:
    - nexpose
    - debug

# How to see what's in the keystore
# /opt/rapid7/nexpose/_jvm*/bin/keytool -list -v -keystore /opt/rapid7/nexpose/_jvm*/lib/security/cacerts
# Default password is 'changeit'
